/**
 * Centralized Database Configuration
 * Store all database table names and configurations in one place for easy management
 */

export const dbConfig = {
  // All 279 table names
  tables: {
    ab_test_configs: 'ab_test_configs',
    ad_campaigns: 'ad_campaigns',
    admin_roles: 'admin_roles',
    admin_users: 'admin_users',
    affiliate_clicks: 'affiliate_clicks',
    affiliate_partners: 'affiliate_partners',
    ai_conversations: 'ai_conversations',
    ai_generated_content: 'ai_generated_content',
    ai_messages: 'ai_messages',
    ai_product_recommendations: 'ai_product_recommendations',
    ai_usage_stats: 'ai_usage_stats',
    api_keys: 'api_keys',
    api_usage_logs: 'api_usage_logs',
    audit_logs: 'audit_logs',
    authorized_apps: 'authorized_apps',
    badges: 'badges',
    bank_accounts: 'bank_accounts',
    bnpl_plans: 'bnpl_plans',
    calendar_events: 'calendar_events',
    captcha_challenges: 'captcha_challenges',
    chat_conversations: 'chat_conversations',
    chat_messages: 'chat_messages',
    circle_members: 'circle_members',
    cohort_data: 'cohort_data',
    collaborative_tasks: 'collaborative_tasks',
    collection_items: 'collection_items',
    community_comments: 'community_comments',
    community_likes: 'community_likes',
    community_posts: 'community_posts',
    competitor_insights: 'competitor_insights',
    content_filters: 'content_filters',
    content_posts: 'content_posts',
    content_reports: 'content_reports',
    content_versions: 'content_versions',
    country_settings: 'country_settings',
    coupon_usage_history: 'coupon_usage_history',
    cron_job_logs: 'cron_job_logs',
    crypto_transactions: 'crypto_transactions',
    currencies: 'currencies',
    customer_support_tickets: 'customer_support_tickets',
    daily_user_activities: 'daily_user_activities',
    dashboard_widgets: 'dashboard_widgets',
    data_exports: 'data_exports',
    data_retention_policies: 'data_retention_policies',
    developer_apps: 'developer_apps',
    developer_keys: 'developer_keys',
    direct_debit_mandates: 'direct_debit_mandates',
    discount_codes: 'discount_codes',
    email_bounces: 'email_bounces',
    email_campaigns: 'email_campaigns',
    email_deliveries: 'email_deliveries',
    email_templates: 'email_templates',
    embedded_payments: 'embedded_payments',
    encryption_keys: 'encryption_keys',
    event_registrations: 'event_registrations',
    events: 'events',
    external_auth_providers: 'external_auth_providers',
    external_profiles: 'external_profiles',
    faqs: 'faqs',
    featured_products: 'featured_products',
    feed_items: 'feed_items',
    feedback: 'feedback',
    file_uploads: 'file_uploads',
    financial_reports: 'financial_reports',
    friendship_requests: 'friendship_requests',
    game_leaderboards: 'game_leaderboards',
    gift_cards: 'gift_cards',
    group_memberships: 'group_memberships',
    groups: 'groups',
    guest_sessions: 'guest_sessions',
    identities: 'identities',
    identity_verification_logs: 'identity_verification_logs',
    invoice_items: 'invoice_items',
    invoices: 'invoices',
    jobs: 'jobs',
    job_applications: 'job_applications',
    kyc_documents: 'kyc_documents',
    leaderboard_entries: 'leaderboard_entries',
    learning_modules: 'learning_modules',
    linked_services: 'linked_services',
    live_streams: 'live_streams',
    location_analytics: 'location_analytics',
    log_entries: 'log_entries',
    loyalty_programs: 'loyalty_programs',
    marketplace_listings: 'marketplace_listings',
    merchant_accounts: 'merchant_accounts',
    messaging_conversations: 'messaging_conversations',
    messaging_messages: 'messaging_messages',
    mobile_app_versions: 'mobile_app_versions',
    multi_factor_auth: 'multi_factor_auth',
    news_articles: 'news_articles',
    notification_preferences: 'notification_preferences',
    oauth_access_tokens: 'oauth_access_tokens',
    oauth_authorization_codes: 'oauth_authorization_codes',
    oauth_clients: 'oauth_clients',
    oauth_refresh_tokens: 'oauth_refresh_tokens',
    offline_sync_logs: 'offline_sync_logs',
    one_time_passwords: 'one_time_passwords',
    organization_invites: 'organization_invites',
    organizations: 'organizations',
    partner_integrations: 'partner_integrations',
    password_reset_tokens: 'password_reset_tokens',
    payment_gateways: 'payment_gateways',
    payment_intents: 'payment_intents',
    payment_methods: 'payment_methods',
    payment_refunds: 'payment_refunds',
    payment_sessions: 'payment_sessions',
    payment_transactions: 'payment_transactions',
    personal_access_tokens: 'personal_access_tokens',
    personalized_recommendations: 'personalized_recommendations',
    phone_verification_codes: 'phone_verification_codes',
    photo_albums: 'photo_albums',
    photo_tags: 'photo_tags',
    photos: 'photos',
    platform_configurations: 'platform_configurations',
    post_reactions: 'post_reactions',
    posts: 'posts',
    privacy_controls: 'privacy_controls',
    product_categories: 'product_categories',
    product_images: 'product_images',
    product_inventory: 'product_inventory',
    product_prices: 'product_prices',
    product_ratings: 'product_ratings',
    product_reviews: 'product_reviews',
    products: 'products',
    project_collaborators: 'project_collaborators',
    projects: 'projects',
    push_notification_logs: 'push_notification_logs',
    push_subscriptions: 'push_subscriptions',
    qr_codes: 'qr_codes',
    queue_jobs: 'queue_jobs',
    referral_codes: 'referral_codes',
    report_abuse: 'report_abuse',
    report_analytics: 'report_analytics',
    reports: 'reports',
    reward_programs: 'reward_programs',
    role_permissions: 'role_permissions',
    roles: 'roles',
    scheduled_emails: 'scheduled_emails',
    scheduled_jobs: 'scheduled_jobs',
    scheduled_messages: 'scheduled_messages',
    scheduled_reports: 'scheduled_reports',
    sdk_downloads: 'sdk_downloads',
    security_alerts: 'security_alerts',
    seo_settings: 'seo_settings',
    shared_workspaces: 'shared_workspaces',
    shipment_tracking_events: 'shipment_tracking_events',
    shopping_list_items: 'shopping_list_items',
    smart_shopping_lists: 'smart_shopping_lists',
    sms_queue: 'sms_queue',
    sso_activity_logs: 'sso_activity_logs',
    sso_sessions: 'sso_sessions',
    sso_tokens: 'sso_tokens',
    sso_user_sessions: 'sso_user_sessions',
    story_views: 'story_views',
    subscription_plans: 'subscription_plans',
    support_agents: 'support_agents',
    support_ticket_messages: 'support_ticket_messages',
    survey_responses: 'survey_responses',
    surveys: 'surveys',
    system_health_logs: 'system_health_logs',
    tax_config: 'tax_config',
    translations: 'translations',
    user_2fa: 'user_2fa',
    user_2fa_attempts: 'user_2fa_attempts',
    user_ab_tests: 'user_ab_tests',
    user_account_deletion_schedule: 'user_account_deletion_schedule',
    user_account_history: 'user_account_history',
    user_account_recovery: 'user_account_recovery',
    user_account_recovery_options: 'user_account_recovery_options',
    user_activity_history: 'user_activity_history',
    user_activity_logs: 'user_activity_logs',
    user_ad_interactions: 'user_ad_interactions',
    user_ad_personalization: 'user_ad_personalization',
    user_addresses: 'user_addresses',
    user_ai_interactions: 'user_ai_interactions',
    user_ai_preferences: 'user_ai_preferences',
    user_app_access: 'user_app_access',
    user_app_settings: 'user_app_settings',
    user_app_usage_timeline: 'user_app_usage_timeline',
    user_audit_logs: 'user_audit_logs',
    user_automations: 'user_automations',
    user_backup_codes: 'user_backup_codes',
    user_badges: 'user_badges',
    user_behavioral_biometrics: 'user_behavioral_biometrics',
    user_blocks: 'user_blocks',
    user_carbon_footprint: 'user_carbon_footprint',
    user_carts: 'user_carts',
    user_challenge_progress: 'user_challenge_progress',
    user_circles: 'user_circles',
    user_collections: 'user_collections',
    user_compare_lists: 'user_compare_lists',
    user_connected_apps: 'user_connected_apps',
    user_connections: 'user_connections',
    user_consents: 'user_consents',
    user_content_preferences: 'user_content_preferences',
    user_creator_monetization: 'user_creator_monetization',
    user_credit_scores: 'user_credit_scores',
    user_custom_themes: 'user_custom_themes',
    user_daily_activity: 'user_daily_activity',
    user_data_export_archives: 'user_data_export_archives',
    user_data_portability: 'user_data_portability',
    user_data_promises: 'user_data_promises',
    user_data_requests: 'user_data_requests',
    user_devices: 'user_devices',
    user_digital_wellbeing: 'user_digital_wellbeing',
    user_engagement_scores: 'user_engagement_scores',
    user_events: 'user_events',
    user_export_jobs: 'user_export_jobs',
    user_family_sharing: 'user_family_sharing',
    user_feed_settings: 'user_feed_settings',
    user_feedback: 'user_feedback',
    user_follows: 'user_follows',
    user_game_achievements: 'user_game_achievements',
    user_game_library: 'user_game_library',
    user_goals: 'user_goals',
    user_groups: 'user_groups',
    user_heatmaps: 'user_heatmaps',
    user_identity_verification: 'user_identity_verification',
    user_inactive_account_manager: 'user_inactive_account_manager',
    user_interest_scores: 'user_interest_scores',
    user_invoices: 'user_invoices',
    user_journeys: 'user_journeys',
    user_levels: 'user_levels',
    user_location_history: 'user_location_history',
    user_locations: 'user_locations',
    user_login_methods: 'user_login_methods',
    user_login_notifications: 'user_login_notifications',
    user_loyalty_points: 'user_loyalty_points',
    user_loyalty_transactions: 'user_loyalty_transactions',
    user_mentions: 'user_mentions',
    user_milestones: 'user_milestones',
    user_mutes: 'user_mutes',
    user_notes: 'user_notes',
    user_notification_settings: 'user_notification_settings',
    user_notifications: 'user_notifications',
    user_onboarding: 'user_onboarding',
    user_passkeys: 'user_passkeys',
    user_payment_disputes: 'user_payment_disputes',
    user_payment_methods: 'user_payment_methods',
    user_privacy_settings: 'user_privacy_settings',
    user_product_interactions: 'user_product_interactions',
    user_promo_codes: 'user_promo_codes',
    user_purchase_history_extended: 'user_purchase_history_extended',
    user_purchases: 'user_purchases',
    user_push_tokens: 'user_push_tokens',
    user_recently_viewed: 'user_recently_viewed',
    user_referrals: 'user_referrals',
    user_reports: 'user_reports',
    user_reputation: 'user_reputation',
    user_reviews: 'user_reviews',
    user_rfm_history: 'user_rfm_history',
    user_saved_cards_extended: 'user_saved_cards_extended',
    user_saved_places: 'user_saved_places',
    user_saved_searches: 'user_saved_searches',
    user_screen_time: 'user_screen_time',
    user_search_history: 'user_search_history',
    user_security_activity: 'user_security_activity',
    user_security_checkup: 'user_security_checkup',
    user_security_questions: 'user_security_questions',
    user_segments: 'user_segments',
    user_session_preferences: 'user_session_preferences',
    user_sessions: 'user_sessions',
    user_sessions_extended: 'user_sessions_extended',
    user_social_accounts: 'user_social_accounts',
    user_social_graph: 'user_social_graph',
    user_storage_usage: 'user_storage_usage',
    user_stories: 'user_stories',
    user_streaks: 'user_streaks',
    user_subscription_boxes: 'user_subscription_boxes',
    user_subscription_history: 'user_subscription_history',
    user_subscriptions: 'user_subscriptions',
    user_support_tickets: 'user_support_tickets',
    user_third_party_permissions: 'user_third_party_permissions',
    user_trusted_contacts: 'user_trusted_contacts',
    user_trusted_devices: 'user_trusted_devices',
    user_voice_activity: 'user_voice_activity',
    user_wallet_transactions: 'user_wallet_transactions',
    user_wallets: 'user_wallets',
    user_wishlist_lists: 'user_wishlist_lists',
    user_wishlists: 'user_wishlists',
    users: 'users',
    video_calls: 'video_calls',
    virtual_try_on_history: 'virtual_try_on_history',
    voice_messages: 'voice_messages',
    webhooks: 'webhooks',
    whatsapp_queue: 'whatsapp_queue',
    workspace_members: 'workspace_members',
    zipra_apps: 'zipra_apps',
    zipra_products: 'zipra_products',
  },

  // Column names for common tables
  columns: {
    users: {
      id: 'id',
      email: 'email',
      username: 'username',
      password_hash: 'password_hash',
      created_at: 'created_at',
      updated_at: 'updated_at',
      last_login: 'last_login',
      is_active: 'is_active',
      email_verified: 'email_verified',
      phone_verified: 'phone_verified',
    },
    profiles: {
      id: 'id',
      user_id: 'user_id',
      first_name: 'first_name',
      last_name: 'last_name',
      display_name: 'display_name',
      bio: 'bio',
      avatar_url: 'avatar_url',
      birth_date: 'birth_date',
      gender: 'gender',
      timezone: 'timezone',
      locale: 'locale',
    },
    addresses: {
      id: 'id',
      user_id: 'user_id',
      street: 'street',
      city: 'city',
      state: 'state',
      zip_code: 'zip_code',
      country: 'country',
      is_default: 'is_default',
      address_type: 'address_type',
    },
    payment_methods: {
      id: 'id',
      user_id: 'user_id',
      type: 'type',
      provider: 'provider',
      masked_number: 'masked_number',
      expiry_month: 'expiry_month',
      expiry_year: 'expiry_year',
      is_default: 'is_default',
      created_at: 'created_at',
    },
    orders: {
      id: 'id',
      user_id: 'user_id',
      order_number: 'order_number',
      status: 'status',
      total_amount: 'total_amount',
      currency: 'currency',
      created_at: 'created_at',
      updated_at: 'updated_at',
    },
  },

  // Database connection settings
  connection: {
    host: 'localhost', // Default host - can be overridden in environment
    port: 5432, // Default PostgreSQL port
    database: 'zpria_account_db', // Default database name
    username: 'postgres', // Default username
    password: '', // Default password
    ssl: false, // SSL setting
  },

  // Supabase configuration
  supabase: {
    url: 'https://ojiswabilogpeidzhidu.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaXN3YWJpbG9ncGVpZHpoaWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNzQ4NDAsImV4cCI6MjA4NDg1MDg0MH0.VF0JsThZjrGgCe9kQHrf5mdrwpwE4ZWwmtn20B64l30',
  },

  // Query configuration
  query: {
    defaultLimit: 20,
    maxLimit: 100,
    timeout: 30000, // 30 seconds
  },

  // Indexes configuration
  indexes: {
    users: {
      email: 'idx_users_email',
      username: 'idx_users_username',
      created_at: 'idx_users_created_at',
    },
    profiles: {
      user_id: 'idx_profiles_user_id',
    },
    addresses: {
      user_id: 'idx_addresses_user_id',
      is_default: 'idx_addresses_is_default',
    },
  },
};

// Export specific table names as constants for convenience
export const TABLES = dbConfig.tables;

// Export commonly used column sets
export const USER_COLUMNS = dbConfig.columns.users;
export const PROFILE_COLUMNS = dbConfig.columns.profiles;
export const ADDRESS_COLUMNS = dbConfig.columns.addresses;
export const PAYMENT_METHOD_COLUMNS = dbConfig.columns.payment_methods;
export const ORDER_COLUMNS = dbConfig.columns.orders;